#spring:
#  # Project: name
#  application:
#    name: sijak
#  # Mysql: set up
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://3.35.129.224:3306/sijak
#    username: dt10002
#    password: 1234
#  # JPA: set up
#  jpa:
#    show-sql: true
#    database: mysql
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        transaction:
#          jta:
#            platform: org.hibernate.service.jta.JtaPlatform
#
#  # swagger info
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#
#  # Kakao OAuth2
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: e3bc4f1f66bd3e98f266271f5cb805dc     # REST API KEY
#            client-secret: WAsjWmT9l3RY92bgYkksbDOLMR0dZDik # CLIENT SECRET KEY
#            client-authentication-method: client_secret_post
#            client-name: Kakao
#            redirect-uri: https://sijak.app/login/callback
#            authorization-grant-type: authorization_code
#            scope:
#              - profile_nickname # 닉네임
#              - profile_image    # 프로필 사진
#              - account_email    # 카카오계정(이메일)
#              - name             # 이름
#              - gender           # 성별
#              - age_range        # 연령대
#
#        # Kakao OAuth2 Provider
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
#
#
## logback info
#logging:
#  config: classpath:logback-spring.xml
#
## fontend server
#front:
#  server: https://sijak.vercel.app
#
#
#
## private key
#client-id: e3bc4f1f66bd3e98f266271f5cb805dc
#redirect-uri: https://sijak.app/login/callback
#client-secret: WAsjWmT9l3RY92bgYkksbDOLMR0dZDik
#token_uri: https://kauth.kakao.com/oauth/token
#user_info_uri: https://kapi.kakao.com/v2/user/me
#jwt:
#  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
#
#server:
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-store-password: golddoor9511.
#  address: 0.0.0.0
#  port: 8080
#
#
